### ISSUE TITLE
Release new major release that drops Node below 14

### ISSUE THREAD

**Issue by voxpelli** [alexbrazier/simple-update-notifier#13]
As a follow up to #12:

I would suggest updating to support only the latest LTS and later. The `1.x` branch can still be maintained for those in need of support for older, but for the rest of us it would be neat to support the actual features of a modern day Node.js release.

That would convert this monstrosity of a code:

```javascript
var simpleUpdateNotifier = function (args) { return __awaiter(void 0, void 0, void 0, function () {
    var latestVersion;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                if (!args.alwaysRun &&
                    (!process.stdout.isTTY || (isNpmOrYarn && !args.shouldNotifyInNpmScript))) {
                    return [2 /*return*/];
                }
                _b.label = 1;
            case 1:
                _b.trys.push([1, 3, , 4]);
                return [4 /*yield*/, hasNewVersion(args)];
            case 2:
                latestVersion = _b.sent();
                if (latestVersion) {
                    console.log(borderedText("New version of ".concat(args.pkg.name, " available!\nCurrent Version: ").concat(args.pkg.version, "\nLatest Version: ").concat(latestVersion)));
                }
                return [3 /*break*/, 4];
            case 3:
                _b.sent();
                return [3 /*break*/, 4];
            case 4: return [2 /*return*/];
        }
    });
}); };
```

Into this one that is pretty much the TS code minus type annotations (assuming one uses [`target: es2020`](https://github.com/tsconfig/bases/blob/main/bases/node14.json)):

```javascript
const simpleUpdateNotifier = async (args) => {
    if (!args.alwaysRun &&
        (!process.stdout.isTTY || (isNpmOrYarn && !args.shouldNotifyInNpmScript))) {
        return;
    }
    try {
        const latestVersion = await hasNewVersion(args);
        if (latestVersion) {
            console.log(borderedText(`New version of ${args.pkg.name} available!
Current Version: ${args.pkg.version}
Latest Version: ${latestVersion}`));
        }
    }
    catch {
        // Catch any network errors or cache writing errors so module doesn't cause a crash
    }
};
```

I would do what is suggested in[ this tweet from @MylesBorins](https://twitter.com/MylesBorins/status/1521619664723402753):

> Also fwiw here is what I suggest you use for the engines field when you drop 12 support and bump a semver major. Guarantees `node:` namespace support for 14+
>
> ```json
> "engines": {
>   "node": "^14.18 || ^16.13 || >=18"
> }
> ```

I myself have simplified that to: [`^14.18.0 || >=16.0.0`](https://github.com/voxpelli/node-connect-pg-simple/blob/0e5c628e0feca59f6ecd51c8256089caa9905410/package.json#L21)

Then you can use `node:` prefix for imports, you can use `await import()` if you need to import an ESM module etc.

**Comment by alexbrazier** [comment]
The package is now on the latest version of all dependences and supports the lowest version of node possible - bumped from node 8 to node 10 in version `2.0.0`.

This package mostly exists to support more packages that don't want to force everyone to upgrade to the latest version of node if they are stuck on an older version for some reason. I recommend using the original update-notifier which moved to ESM and dropped everything below node 14 if you don't want the transpiled version. I will close this as a wont fix for now and re-review if packages depending on it start to move to newer node versions.
