### ISSUE TITLE
Security advice semver

### ISSUE THREAD

**Issue by NormandoHall** [alexbrazier/simple-update-notifier#20]
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

```
  simple-update-notifier  >=1.0.7
  Depends on vulnerable versions of semver
```

**Comment by alexbrazier** [comment]
Closed by #19 

Fixed in version [2.0.0](https://github.com/alexbrazier/simple-update-notifier/releases/tag/v2.0.0)
